# Generated by Django 4.0.1 on 2022-01-29 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predictionsJSON', models.TextField()),
                ('datafile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict.datafile')),
            ],
        ),
    ]
