# Generated by Django 4.0.1 on 2022-01-29 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_datapredictions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataPredictions',
            new_name='DataPrediction',
        ),
    ]
