# Generated by Django 4.0.1 on 2022-01-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_runningjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='description',
            field=models.CharField(default='Some default description of the project', max_length=300),
        ),
    ]
